version: '3.8'
services:
  nodejs-app:
    restart: always
    build: 
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: todo-app
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"